version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EMBLY_USER: $EMBLY_USER
    volumes:
      - ../:/go/src/github.com/maxmcd/embly/
      - control:/go/pkg/
      - homecache:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  control: {}
  homecache: {}

networks:
  default:
    external:
      name: embly
