version: "3.3"

services:
  api:
    build:
      context: ./
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - DB_DISABLE_SSL=truthy
      - DB_HOST=postgres
      - DB_PASSWORD=postgresi
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - ENV=dev
      - REDIS_HOST=redis:6379
  redis:
    image: redis:5.0.4
    # https://redis.io/topics/persistence
    command: redis-server --appendonly yes
    restart: always
    expose:
      - "6379"
    volumes:
      - redis:/data
  postgres:
    image: postgres:10.3
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      # - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable

volumes:
  redis: {}
  postgres: {}
